name: npm Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Update version in package.json
        run: |
          VERSION=$(jq -r '.version' package.json | sed -E "s/0$/${GITHUB_RUN_NUMBER}/")
          jq ".version = \"$VERSION\"" package.json > tmp.json && mv tmp.json package.json
        shell: bash